### ISSUE TITLE
Can you share the preprocessing part for the data? 

### ISSUE THREAD

**Issue by coreqode** [dichotomies/NeuralDiff#1]
Hi, this is awesome work!. 
I wanted to train this model in my own dataset. Can you share the script for preprocessing and camera parameters extraction (COLMAP) part?

Thanks

**Comment by dichotomies** [comment]
Hi, thanks, I'm glad you like our work!

One question, I guess you mean that you have the COLMAP reconstruction for a scene and would like to transform it into our format (i.e. you would like to extract near/far bounds, camera poses and intrinsics from COLMAP and use this data with our model)?

**Comment by coreqode** [comment]
Yes exactly! I already have COLMAP reconstructions.
